### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by calee0219** [KHC-ZhiHao/HanCount#2]
Add a donate button such as paypal (https://www.paypal.com/tw/webapps/mpp/paypal-me) or blockchain address to earn some donate!!!

May the wealth be with Kaohsiung.

**Comment by terrylinooo** [comment]
Sending money is not allowed from accounts both are from Taiwan because of the financial policy of the Taiwan government.

However, you can still put the following URL on your website to receive a donation from other countries.

h ttps://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=**{your email associated to your PayPal account}**&item_name=**{any text you want to display to donators}**&currency_code=USD&source=url

**Comment by KHC-ZhiHao** [comment]
能有１５０顆星星就讓我很詫異了，沒有打算接受贊助，謝謝關心
